title: kriswrightdev.com
email: kris.al.wright@gmail.com
description: A personal blog and portfolio for Kristoffer A. Wright.
url: 'https://kawright.github.io'
github_username: kawright
permalink: /:collection/:year-:month-:day-:title:output_ext
show_excerpts: true
style: dark
markdown: kramdown
remote_theme: b2a3e8/jekyll-theme-console
header_pages:
  - index.md
  - resume.md
  - projects.md
  

footer: 'Copyright 2022 - Kristoffer A. Wright'